chec tests

diff --git a/.github/workflows/assignment3.yml b/.github/workflows/assignment3.yml
--- a/.github/workflows/assignment3.yml
+++ b/.github/workflows/assignment3.yml
@@ -74,14 +74,21 @@ jobs:
 
       - name: Ensure test scripts are executable
         run: chmod +x tests/*.py
+
       - name: Run tests
         run: |
           cd tests
-          pytest -v assn3_tests.py > /tmp/assn3_test_results.txt
-          if [ $? -eq 0 ]; then
-            echo "tests succeeded" >> log-file/log.txt
+         if [ -f assn3_tests.py ]; then
+            pytest -v assn3_tests.py > /tmp/assn3_test_results.txt
+            if [ $? -eq 0 ]; then
+              echo "tests succeeded" >> ../log.txt
+            else
+              echo "tests failed" >> ../log.txt
+              cat /tmp/assn3_test_results.txt >> ../log.txt
+              exit 1
+            fi
           else
-            echo "tests failed" >> log-file/log.txt
+            echo "Test file not found" >> ../log.txt
             exit 1
           fi
 
