fixed test result file

diff --git a/.github/workflows/assignment3.yml b/.github/workflows/assignment3.yml
--- a/.github/workflows/assignment3.yml
+++ b/.github/workflows/assignment3.yml
@@ -83,13 +83,8 @@ jobs:
       - name: Run tests
         run: |
           cd tests
-          pytest -v assn3_tests.py > ../assn3_test_results.txt
-          if [ $? -eq 0 ]; then
-            echo "tests succeeded" >> ../log-file/log.txt
-          else
-            echo "tests failed" >> ../log-file/log.txt
-          fi
-
+          pytest -v assn3_tests.py > ../assn3_test_results.txt || (echo "tests failed" >> ../log-file/log.txt && exit 1)
+          echo "tests succeeded" >> ../log-file/log.txt
       - name: Upload test results
         uses: actions/upload-artifact@v4
         if: always()
