added python set up

diff --git a/.github/workflows/assignment3.yml b/.github/workflows/assignment3.yml
--- a/.github/workflows/assignment3.yml
+++ b/.github/workflows/assignment3.yml
@@ -65,22 +65,33 @@ jobs:
             echo "Container failed to run" >> log-file/log.txt
             exit 1
           fi
+
+      - name: Set up Python
+        run: |
+            python -m pip install --upgrade pip
+            pip install pytest requests
+            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+
       - name: Run tests
         run: |
-          docker-compose exec books pytest -v tests/assn3_tests.py > /tmp/assn3_test_results.txt
+          cd tests
+          pytest -v assn3_tests.py > /tmp/assn3_test_results.txt
           if [ $? -eq 0 ]; then
-            echo "tests succeeded" >> log-file/log.txt
+            echo "tests succeeded" >> log.txt
           else
-            echo "tests failed" >> log-file/log.txt
+            echo "tests failed" >> log.txt
+            exit 1
           fi
 
       - name: Upload test results
         uses: actions/upload-artifact@v4
+        if: always()
         with:
           name: test-results
           path: assn3_test_results.txt
 
       - name: Upload log file after test
+        if: always()
         uses: actions/upload-artifact@v4
         with:
           name: log-file
